### ISSUE TITLE
Mac terminal still misses icons

### ISSUE THREAD

**Issue by nicolinux** [lxbrtsch/Menlo-for-Powerline#3]
Hi,
I've installed the font but the small icons still don't appear (using the fish shell with the omf theme "bob-the-fish"). Actually I've never had any powerline-patched font display those nice icons in the terminal.app. It only works in iTerm2. It might be a limitation of the default terminal app and not related to your patched font.
![Screenshot](http://i.imgur.com/GSS4tMc.png)

**Comment by lxbrtsch** [comment]
Looks like you should be able to change the terminal font. [This article](http://osxdaily.com/2011/09/02/use-any-font-in-the-mac-os-x-lion-terminal/) should give some details on how to do that. If the problem persists, please let me know. Otherwise feel free to close the issue.

**Comment by nicolinux** [comment]
Ahm... thanks? This basically just tells you to open the preferences and pick a new font. You don't think I thought of that? :)
I am closing the issue anyway since I don't think it is related to your font.

**Comment by lxbrtsch** [comment]
It seems to be working in OS X 10.11.5 in `terminal.app`. I'll take a longer look into in the morning and see if I can figure anything else out. Sorry about that!
<img width="682" alt="screenshot 2016-08-08 02 06 39" src="https://cloud.githubusercontent.com/assets/567107/17474840/e8a782f0-5d0c-11e6-8e47-2831df23242f.png">

**Comment by nicolinux** [comment]
Ok, many thanks.

**Comment by lxbrtsch** [comment]
So, I've got the font working using Solarized Dark for Terminal.app with the font set to Menlo Regular for Powerline. I'm using agnoster in zsh, a theme that bob-the-fish seems to have been built on. (The alignment is a bit off, but that's been a problem I've been putting off fixing.)

<img width="682" alt="screenshot 2016-08-08 21 16 56" src="https://cloud.githubusercontent.com/assets/567107/17504432/9ab4f3b0-5dad-11e6-8e00-2a55c21ab340.png">
<img width="777" alt="screenshot 2016-08-08 21 17 57" src="https://cloud.githubusercontent.com/assets/567107/17504433/9abd3cfa-5dad-11e6-9a92-c0fc2cf240ec.png">

I'm sorry the font isn't working for you. If you have any other information that could possibly give me more information, I'd love to help more.

**Comment by nicolinux** [comment]
Ok, this might be a OS X 10.11.6 problem. I can't get it to work with any other powerline patched font either.

**Comment by lxbrtsch** [comment]
I just upgraded to 10.11.6 and it still works on my side. One thing to check may be that your Terminal.app theme is set to use Unicode: 
<img width="777" alt="screenshot 2016-08-10 09 26 35" src="https://cloud.githubusercontent.com/assets/567107/17561786/8ce176d4-5edc-11e6-8a66-ba0fcd58892b.png">
I forget whether or not this is an OS X default setting...
